In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]

In [3]:
my_array1=np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2=[11,22,33,44]

In [6]:
#Multidimensional lists
my_lists=[my_list1,my_list2] 

In [7]:
my_array2=np.array(my_lists)

In [8]:
#multidimensional arrays
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
#What kind of matrix is this? 
#2 rows and 4 columns
my_array2.shape

(2, 4)

In [12]:
#What is the datatype? 
my_array2.dtype

dtype('int64')

In [13]:
#making an array with 0's in it
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
my_zeros_array=np.zeros(5)

In [16]:
#checking the datatype
my_zeros_array.dtype

dtype('float64')

In [18]:
#making 5x5 array with 1's in it
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
my_ones_array=np.ones([5,5])

In [22]:
my_ones_array.dtype

dtype('float64')

In [23]:
#same as creating 0's but we can use .empty()
np.empty([5,9])

array([[  3.10503618e+231,  -1.73059685e-077,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.48440497e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076],
       [  1.39804329e-076,   1.39804329e-076,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076],
       [  1.39804329e-076,   1.39804329e-076,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076],
       [  1.39804329e-076,   9.73040728e-072,   9.73041595e-072,
          9.73041595e-072,   1.48474364e-076,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076],
       [  9.72819642e-072,   9.73041595e-072,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   1.39804329e-076,
          1.39804329e-076,   1.39804329e-076,   0.00000000e+000]])

In [24]:
#creating identity matrix
#(just enter one no as it is a square matrix)
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [27]:
# creates an array of numbers with start, stop and step size
#between each number
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])