In [11]:
import numpy as np
import pandas as pd

In [12]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [14]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [15]:
A=np.random.randn(10)
A

array([ 0.45129035,  0.6054451 ,  0.33839384,  0.65765662,  0.5313349 ,
       -1.13432531, -1.88628427, -0.8086509 ,  1.14926931, -0.09106925])

In [18]:
B=np.random.randn(10)
B

array([ 0.8141955 ,  0.26187009, -0.21824579, -1.09130015, -0.22856522,
        0.79243052,  1.75162968,  1.07297815,  0.04275682, -0.71939335])

# Binary Functions

In [19]:
np.add(A,B)

array([ 1.26548585,  0.86731519,  0.12014806, -0.43364353,  0.30276968,
       -0.34189479, -0.13465459,  0.26432725,  1.19202613, -0.8104626 ])

In [20]:
np.maximum(A,B)

array([ 0.8141955 ,  0.6054451 ,  0.33839384,  0.65765662,  0.5313349 ,
        0.79243052,  1.75162968,  1.07297815,  1.14926931, -0.09106925])

In [21]:
np.minimum(A,B)

array([ 0.45129035,  0.26187009, -0.21824579, -1.09130015, -0.22856522,
       -1.13432531, -1.88628427, -0.8086509 ,  0.04275682, -0.71939335])

In [24]:
website="http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [23]:
website="http://www.google.com"
import webbrowser
webbrowser.open(website)

True